eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
spring:
  application:
    name: account
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      username: admin
      password: admin@123
  rabbitmq:
    host: localhost
    username: admin
    password: password
    port: 5672
  kafka:
    bootstrap-servers: localhost:29093,localhost:39093,localhost:49093
    security:
      protocol: SSL
    ssl:
      trust-store-location: classpath:kafka.server.truststore.jks
      trust-store-password: password123
      key-store-location: classpath:kafka.server.keystore.jks
      key-store-password: password123
      key-password: password123
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: false
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false
        spring.json.value.default.type: java.lang.Object
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        schema.registry.url: http://localhost:8081
        spring.json.add.type.headers: false
    properties:
      schema.registry.url: http://localhost:8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  level:
    kh:
      edu:
        cstad:
          account: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"